import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { config } from "@fortawesome/fontawesome-svg-core";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Inter } from "next/font/google";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "厨二病ジェネレータ",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={`${GeistSans.variable}`}>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="container mx-auto max-w-screen-md flex-1 px-2">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
